name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on:  ${{ matrix.os }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version:  ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -o build/onf ./cmd

    - name: run
      run: ./build/onf -h
    
    # step 2: generate build files
    # - name: Generate build files
    #   uses: thatisuday/go-cross-build@v1
    #   with:
    #       platforms: 'linux/amd64, darwin/amd64, windows/amd64'
    #       package: 'onf-package'
    #       name: 'onf'
    #       compress: 'true'
    #       dest: 'dist'
    
    # step 3: upload build-artifacts
    # - uses: wangyoucao577/go-release-action@v1.11
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     goos: linux
    #     goarch: amd64
    #     project_path: "./cmd/"
    #     binary_name: "test-binary"