name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x]
        #[macos,ubuntu, windows]
        os: [ubuntu]
        onf-version: [v0.1.0]
    runs-on:  ${{ matrix.os }}-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version:  ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: read version
      uses: pCYSl5EDgo/cat@master
        id: onf-version
        with:
          path: VERSION

    # - name: build
    #   run: go build -o build/onf-${{ matrix.os }}-${{matrix.onf-version}} ./cmd

    - name: build linux
      run: sh ./scripts/build/linux.sh
    - name: build macos
      run: sh ./scripts/build/osx.sh
    - name: build window
      run: sh ./scripts/build/windows.sh

    - name: chmod +x
      run: chmod +x ./build/*

    # - name: test
    #   run: ./build/onf-${{ matrix.os }}-${{matrix.onf-version}} -h
    
    - name: upload
      env:
        VERSION: ${{ steps.onf-version.outputs.text }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{VERSION}}"
        prerelease: false
        files: |
          ./build/*
